// USER DATA RELATED ACTION TYPES
export const GET_ACCESS_TOKEN = 'GET_ACCESS_TOKEN';
export const GET_ATHLETE      = 'GET_ATHLETE';
export const SET_USER_ERROR   = 'SET_USER_ERROR';
export const UPDATE_ATHLETE   = 'UPDATE_ATHLETE';